import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import {
  AppShell,
  AppShellFooter,
  AppShellHeader,
  AppShellMain,
  ColorSchemeScript,
  Container,
} from '@mantine/core';
import { Providers } from '@/components/providers';
import { getLanguagesStaticParams } from '@/i18n/helpers';
import { ReactNode } from 'react';
import { I18nProps } from '@/types/types';

export const generateStaticParams = getLanguagesStaticParams;

const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
  params: I18nProps;
};

const RootLayout = async ({ children, params: { lang } }: RootLayoutProps) => {
  return (
    <html lang={lang} className={inter.className}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <Providers>
          <AppShell>
            <AppShellHeader
              pos={{ base: 'static', md: 'fixed' }}
              withBorder={false}
              style={{ boxShadow: '0px 2px 8px 0px rgba(0, 0, 0, 0.12)' }}
              zIndex={250}
            >
              <Container maw={'100%'} pl={24} pr={24}>
                HEADER
              </Container>
            </AppShellHeader>
            <AppShellMain pos={'relative'} mt={{ base: 0, md: 50 }}>
              {children}
            </AppShellMain>
            <AppShellFooter withBorder={false} pos={'static'}>
              FOOTER
            </AppShellFooter>
          </AppShell>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
